Repository MicrosoftDocs/azure-docs.ko-kr, pull requests merged in 2018-06, with the labels that each got.

#87 Refined awkward Korean words.
  articles/machine-learning/data-science-virtual-machine/deep-learning-dsvm-overview.md
Labels: Accepted, Linguistic Suggestion

#88 Update overview.md
  articles/machine-learning/team-data-science-process/overview.md
Labels: In Progress, Linguistic Suggestion

#89 Update overview.md
  articles/machine-learning/team-data-science-process/overview.md
Labels: Accepted, Linguistic Suggestion

#104 incorrect translation for 'button'
  articles/app-service/web-sites-dotnet-troubleshoot-visual-studio.md
Labels: Accepted, Linguistic Suggestion

#153 translation for 'duration'
  articles/sql-database/sql-database-query-performance.md
Labels: Accepted, Linguistic Suggestion

#152 re-translated
  articles/sql-database/sql-database-query-performance.md
Labels: Accepted, Linguistic Suggestion

#149 re-translated
  articles/sql-database/sql-database-query-performance.md
Labels: Accepted, Linguistic Suggestion

#148 re-translated
  articles/sql-database/sql-database-query-performance.md
Labels: Accepted, Linguistic Suggestion

#93 translation for 'web app'
  articles/app-service/web-sites-dotnet-troubleshoot-visual-studio.md
Labels: In Progress, Linguistic Suggestion

#94 translation for 'including'
  articles/app-service/web-sites-dotnet-troubleshoot-visual-studio.md
Labels: Accepted, Linguistic Suggestion

#95 translation for 'work'
  articles/app-service/web-sites-dotnet-troubleshoot-visual-studio.md
Labels: Accepted, Linguistic Suggestion

#96 unnecessary translation
  articles/app-service/web-sites-dotnet-troubleshoot-visual-studio.md
Labels: Accepted, Linguistic Suggestion

#97 translation for 'in 48-hour period'
  articles/app-service/web-sites-dotnet-troubleshoot-visual-studio.md
Labels: Accepted, Linguistic Suggestion

#98 translation for 'period'
  articles/app-service/web-sites-dotnet-troubleshoot-visual-studio.md
Labels: Accepted, Linguistic Suggestion

#99 context review
  articles/app-service/web-sites-dotnet-troubleshoot-visual-studio.md
Labels: Accepted, Linguistic Suggestion

#100 incorrect translation, the word order is wrong.
  articles/app-service/web-sites-dotnet-troubleshoot-visual-studio.md
Labels: Accepted, Linguistic Suggestion

#101 too many duplicate words
  articles/app-service/web-sites-dotnet-troubleshoot-visual-studio.md
Labels: Accepted, Linguistic Suggestion

#102 context review
  articles/app-service/web-sites-dotnet-troubleshoot-visual-studio.md
Labels: Accepted, Linguistic Suggestion

#103 incorrect translation
  articles/app-service/web-sites-dotnet-troubleshoot-visual-studio.md
Labels: Accepted, Linguistic Suggestion

#105 incorrect translation for 'push'
  articles/multi-factor-authentication/end-user/microsoft-authenticator-app-how-to.md
Labels: Accepted, Linguistic Suggestion

#106 grammatically incorrect
  articles/multi-factor-authentication/end-user/microsoft-authenticator-app-how-to.md
Labels: Accepted, Linguistic Suggestion

#107 context review
  articles/multi-factor-authentication/end-user/microsoft-authenticator-app-how-to.md
Labels: Accepted, Linguistic Suggestion

#109 context review
  articles/multi-factor-authentication/end-user/microsoft-authenticator-app-how-to.md
Labels: Accepted, Linguistic Suggestion

#111 context review
  articles/app-service/azure-sdk-dotnet-release-notes-2-9.md
Labels: Accepted, Linguistic Suggestion

#112 incorrect translation
  articles/app-service/azure-sdk-dotnet-release-notes-2-9.md
Labels: Accepted, Linguistic Suggestion

#113 unnecessary translation
  articles/app-service/azure-sdk-dotnet-release-notes-2-9.md
Labels: Accepted, Linguistic Suggestion

#114 re-translated
  articles/app-service/azure-sdk-dotnet-release-notes-2-9.md
Labels: Accepted, Linguistic Suggestion

#118 better translation for 'redeploy'
  articles/app-service/app-service-web-get-started-dotnet.md
Labels: In Progress, Linguistic Suggestion

#119 incorrect translation
  articles/app-service/web-sites-dotnet-troubleshoot-visual-studio.md
Labels: Accepted, Linguistic Suggestion

#144 incorrect translation
  articles/sql-database/sql-database-query-performance.md
Labels: Accepted, Linguistic Suggestion

#120 unnecessary translation
  articles/app-service/web-sites-dotnet-troubleshoot-visual-studio.md
Labels: Accepted, Linguistic Suggestion

#123 long translation with unusual vocabularies
  articles/sql-database/sql-database-develop-cplusplus-simple.md
Labels: In Progress, Linguistic Suggestion

#124 Grammatically incorrect
  articles/sql-database/sql-database-develop-cplusplus-simple.md
Labels: Accepted, Linguistic Suggestion

#125 grammatically incorrect
  articles/sql-database/sql-database-develop-cplusplus-simple.md
Labels: Accepted, Linguistic Suggestion

#126 Incorrect translation
  articles/sql-database/sql-database-develop-cplusplus-simple.md
Labels: Accepted, Linguistic Suggestion

#135 translation is not natural
  articles/sql-database/sql-database-query-performance.md
Labels: Accepted, Linguistic Suggestion

#136 대한 is not required
  articles/sql-database/sql-database-query-performance.md
Labels: Accepted, Linguistic Suggestion

#137 context review
  articles/sql-database/sql-database-query-performance.md
Labels: Accepted, Linguistic Suggestion

#138 translation for 'duration'
  articles/sql-database/sql-database-query-performance.md
Labels: Accepted, Linguistic Suggestion

#139 context review
  articles/sql-database/sql-database-query-performance.md
Labels: Accepted, Linguistic Suggestion

#140 re-translated
  articles/sql-database/sql-database-query-performance.md
Labels: Accepted, Linguistic Suggestion

#141 translation for 'duration'
  articles/sql-database/sql-database-query-performance.md
Labels: Accepted, Linguistic Suggestion

#142 context review
  articles/sql-database/sql-database-query-performance.md
Labels: Accepted, Linguistic Suggestion

#143 context review
  articles/sql-database/sql-database-query-performance.md
Labels: Accepted, Linguistic Suggestion

#145 context review
  articles/sql-database/sql-database-query-performance.md
Labels: Accepted, Linguistic Suggestion

#146 translation for 'performance'
  articles/sql-database/sql-database-query-performance.md
Labels: Accepted, Linguistic Suggestion

#147 context review
  articles/sql-database/sql-database-query-performance.md
Labels: Accepted, Linguistic Suggestion

#92 translation for 'Tutorial'
  articles/app-service/web-sites-dotnet-troubleshoot-visual-studio.md
Labels: Linguistic Suggestion

#121 missing translation
  articles/app-service/web-sites-dotnet-troubleshoot-visual-studio.md
Labels: Accepted, Linguistic Suggestion

#122 incorrect tense
  articles/app-service/web-sites-dotnet-troubleshoot-visual-studio.md
Labels: Accepted, Linguistic Suggestion

#127 re-translated
  articles/sql-database/sql-database-develop-cplusplus-simple.md
Labels: Accepted, Linguistic Suggestion

#128 incorrect translation
  articles/sql-database/sql-database-develop-cplusplus-simple.md
Labels: Accepted, Linguistic Suggestion

#129 re-translated
  articles/sql-database/sql-database-develop-cplusplus-simple.md
Labels: Accepted, Linguistic Suggestion

#130 re-translated
  articles/sql-database/sql-database-develop-cplusplus-simple.md
Labels: Accepted, Linguistic Suggestion

#131 re-translated
  articles/sql-database/sql-database-develop-cplusplus-simple.md
Labels: Accepted, Linguistic Suggestion

#132 re-translated
  articles/sql-database/sql-database-develop-cplusplus-simple.md
Labels: Accepted, Linguistic Suggestion

#133 incorrect translation
  articles/sql-database/sql-database-query-performance.md
Labels: Accepted, Linguistic Suggestion
