Repository MicrosoftDocs/azure-docs.ko-kr, pull requests merged in 2018-04, with the labels that each got.

#75 Fix to proper expressions.
  articles/app-service/app-service-web-get-started-java.md
Labels: Accepted, Linguistic Suggestion

#77 Fix to proper expressions.
  includes/cloud-shell-try-it.md
Labels: Accepted, Linguistic Suggestion

#79 Update tutorial-review-usage.md
  articles/cost-management/tutorial-review-usage.md
Labels: Accepted, Technical Issue

#83 Edit "Azure portal" link to possible
  articles/aks/kubernetes-walkthrough-portal.md
Labels: Accepted, Linguistic Suggestion, Source Issue, Technical Issue
