Repository MicrosoftDocs/azure-docs.ko-kr, pull requests merged in 2019-06, with the labels that each got.

#677 Fix mistranslation
  articles/data-factory/v1/data-factory-pig-activity.md
Labels: Accepted

#674 Fix mistranslation
  articles/data-factory/v1/data-factory-onprem-postgresql-connector.md
Labels: Accepted

#675 Fix mistranslation
  articles/data-factory/v1/data-factory-onprem-sybase-connector.md
Labels: Accepted

#676 Fix mistranslation
  articles/data-factory/v1/data-factory-onprem-teradata-connector.md
Labels: Accepted

#670 Update cognitive-services-containers-configuration-shared-settings-ta…
  includes/cognitive-services-containers-configuration-shared-settings-table.md
Labels: Accepted, Linguistic Suggestion

#645 Update assign-policy-template.md
  articles/governance/policy/assign-policy-template.md
Labels: Accepted, Linguistic Suggestion

#644 Update assign-policy-azurecli.md
  articles/governance/policy/assign-policy-azurecli.md
Labels: Accepted, Linguistic Suggestion

#643 Update assign-policy-powershell.md
  articles/governance/policy/assign-policy-powershell.md
Labels: Accepted, Linguistic Suggestion

#642 Update assign-policy-portal.md
  articles/governance/policy/assign-policy-portal.md
Labels: Accepted, Linguistic Suggestion

#649 Update concept-brand-detection.md
  articles/cognitive-services/Computer-vision/concept-brand-detection.md
Labels: Accepted, Linguistic Suggestion

#648 Update concept-object-detection.md
  articles/cognitive-services/Computer-vision/concept-object-detection.md
Labels: Accepted, Linguistic Suggestion

#647 Update powerbi-visualize.md
  articles/cosmos-db/powerbi-visualize.md
Labels: Accepted, Linguistic Suggestion

#646 Update howto-restart-server-cli.md
  articles/mariadb/howto-restart-server-cli.md
Labels: Accepted, Linguistic Suggestion

#681 Fix mistranslation
  articles/data-factory/v1/data-factory-salesforce-connector.md
Labels: Accepted, Linguistic Suggestion

#682 Fix mistranslation
  articles/data-factory/v1/data-factory-sftp-connector.md
Labels: Accepted, Linguistic Suggestion

#683 Fix mistranslation
  articles/active-directory-b2c/configure-ropc.md
Labels: Accepted, Linguistic Suggestion

#684 Fix mistranslation
  articles/active-directory-b2c/ropc-custom.md
Labels: Accepted, Linguistic Suggestion

#685 Fix mistranslation
  articles/active-directory/develop/active-directory-claims-mapping.md
Labels: Accepted, Linguistic Suggestion

#680 Update cognitive-services-containers-configuration-shared-settings-eu…
  includes/cognitive-services-containers-configuration-shared-settings-eula.md
Labels: Accepted, Linguistic Suggestion

#693 Fix mistranslation
  articles/data-factory/v1/data-factory-stored-proc-activity.md
Labels: Accepted, Linguistic Suggestion

#692 Fix mistranslation
  articles/data-factory/v1/data-factory-sqlserver-connector.md
Labels: Accepted, Linguistic Suggestion

#691 Fix mistranslation
  articles/data-factory/v1/data-factory-spark.md
Labels: Accepted, Linguistic Suggestion

#650 Update create-and-manage.md
  articles/governance/policy/tutorials/create-and-manage.md
Labels: Accepted, Linguistic Suggestion

#657 Update storage-introduction.md
  articles/storage/common/storage-introduction.md
Labels: Accepted, Linguistic Suggestion

#665 Update HowToCallVisionAPI.md
  articles/cognitive-services/Computer-vision/Vision-API-How-to-Topics/HowToCallVisionAPI.md
Labels: Accepted, Linguistic Suggestion

#664 Update concept-recognizing-text.md
  articles/cognitive-services/Computer-vision/concept-recognizing-text.md
Labels: Linguistic Suggestion, Partially Accepted

#667 Update language-support.md
  articles/cognitive-services/Computer-vision/language-support.md
Labels: Accepted, Linguistic Suggestion

#694 Fix mistranslation
  articles/digital-twins/how-to-egress-endpoints.md
Labels: Accepted, Linguistic Suggestion

#701 Fix mistranslation
  articles/event-grid/event-schema-container-registry.md
Labels: Accepted, Linguistic Suggestion

#700 Fix mistranslation
  articles/event-grid/event-schema-blob-storage.md
Labels: Accepted, Linguistic Suggestion

#695 Fix mistranslation
  articles/event-grid/event-schema-azure-maps.md
Labels: Accepted, Linguistic Suggestion

#699 Update csharp-tutorial.md
  articles/cognitive-services/Custom-Vision-Service/csharp-tutorial.md
Labels: Accepted, Technical Issue

#662 Update create-custom-policy-definition.md
  articles/governance/policy/tutorials/create-custom-policy-definition.md
Labels: Accepted, Linguistic Suggestion

#668 Update create-custom-policy-definition.md
  articles/governance/policy/tutorials/create-custom-policy-definition.md
Labels: Accepted, Linguistic Suggestion

#671 Update cognitive-services-containers-request-access.md
  includes/cognitive-services-containers-request-access.md
Labels: Accepted, Linguistic Suggestion

#686 Update index.yml
  articles/azure-functions/index.yml
Labels: Accepted, Linguistic Suggestion

#690 Update computer-vision-resource-container-config.md
  articles/cognitive-services/Computer-vision/computer-vision-resource-container-config.md
Labels: Accepted, Linguistic Suggestion

#689 Update cognitive-services-containers-configuration-shared-settings-lo…
  includes/cognitive-services-containers-configuration-shared-settings-logging.md
Labels: Accepted, Linguistic Suggestion

#688 Update cognitive-services-containers-configuration-shared-settings-ht…
  includes/cognitive-services-containers-configuration-shared-settings-http-proxy.md
Labels: Accepted, Linguistic Suggestion

#687 Update cognitive-services-containers-configuration-shared-settings-fl…
  includes/cognitive-services-containers-configuration-shared-settings-fluentd.md
Labels: Accepted, Linguistic Suggestion

#710 Fix mistranslation
  articles/event-grid/event-schema-service-bus.md
Labels: In Progress

#709 Fix mistranslation
  articles/event-grid/event-schema-resource-groups.md
Labels: In Progress

#708 Fix mistranslation
  articles/event-grid/event-schema-iot-hub.md
Labels: In Progress

#703 Fix mistranslation
  articles/event-grid/event-schema-event-hubs.md
Labels: In Progress

#713 Update functions-create-first-function-python.md
  articles/azure-functions/functions-create-first-function-python.md
Labels: Accepted

#712 Update virtual-machines-managed-disks-types-overview.md
  includes/virtual-machines-managed-disks-types-overview.md
Labels: Accepted, Linguistic Suggestion

#706 Update java-tutorial-od.md
  articles/cognitive-services/Custom-Vision-Service/java-tutorial-od.md
Labels: In Progress

#705 Update java-tutorial.md
  articles/cognitive-services/Custom-Vision-Service/java-tutorial.md
Labels: Accepted

#704 Update get-keys.md
  articles/cognitive-services/Custom-Vision-Service/includes/get-keys.md
Labels: In Progress

#731 Fix mistranslation
  articles/hdinsight/hdinsight-for-vscode.md
Labels: In Progress

#730 Fix mistranslation
  articles/event-grid/event-schema.md
Labels: In Progress

#729 Fix mistranslation
  articles/event-grid/event-schema-subscriptions.md
Labels: In Progress

#715 Update getting-started-improving-your-classifier.md
  articles/cognitive-services/Custom-Vision-Service/getting-started-improving-your-classifier.md
Labels: In Progress

#717 Update custom-vision-onnx-windows-ml.md
  articles/cognitive-services/Custom-Vision-Service/custom-vision-onnx-windows-ml.md
Labels: Accepted, Technical Issue

#697 Update export-your-model.md
  articles/cognitive-services/Custom-Vision-Service/export-your-model.md
Labels: Linguistic Suggestion, Partially Accepted, Technical Issue

#698 Update getting-started-build-a-classifier.md
  articles/cognitive-services/Custom-Vision-Service/getting-started-build-a-classifier.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#714 Update functions-create-first-function-powershell.md
  articles/azure-functions/functions-create-first-function-powershell.md
Labels: Accepted, Linguistic Suggestion

#737 Fix mistranslation
  articles/lab-services/devtest-lab-artifact-author.md
Labels: In Progress

#738 Fix mistranslation
  articles/load-balancer/create-load-balancer-rest-api.md
Labels: In Progress

#739 Fix mistranslation
  articles/logic-apps/logic-apps-custom-api-authentication.md
Labels: In Progress

#716 Update use-prediction-api.md
  articles/cognitive-services/Custom-Vision-Service/use-prediction-api.md
Labels: Accepted, Linguistic Suggestion

#718 Update limits-and-quotas.md
  articles/cognitive-services/Custom-Vision-Service/limits-and-quotas.md
Labels: Accepted, Linguistic Suggestion

#719 Update functions-create-first-azure-function.md
  articles/azure-functions/functions-create-first-azure-function.md
Labels: Accepted, Linguistic Suggestion

#733 Update vs-text-connected-service.md
  articles/cognitive-services/text-analytics/vs-text-connected-service.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#746 Fix mistranslation
  articles/logic-apps/logic-apps-exception-handling.md
Labels: In Progress

#747 Fix mistranslation
  articles/logic-apps/logic-apps-handle-large-messages.md
Labels: In Progress

#748 Fix mistranslation
  articles/logic-apps/logic-apps-track-integration-account-as2-tracking-schemas.md
Labels: In Progress

#749 Fix mistranslation
  articles/logic-apps/logic-apps-track-integration-account-custom-tracking-schema.md
Labels: In Progress

#724 Update functions-create-first-azure-function-azure-cli-linux.md
  articles/azure-functions/functions-create-first-azure-function-azure-cli-linux.md
Labels: Accepted, Linguistic Suggestion

#725 Update text-analytics-how-to-signup.md
  articles/cognitive-services/text-analytics/how-tos/text-analytics-how-to-signup.md
Labels: Accepted, Linguistic Suggestion

#726 Update text-analytics-how-to-language-detection.md
  articles/cognitive-services/text-analytics/how-tos/text-analytics-how-to-language-detection.md
Labels: Linguistic Suggestion, Partially Accepted

#728 Update text-analytics-how-to-keyword-extraction.md
  articles/cognitive-services/text-analytics/how-tos/text-analytics-how-to-keyword-extraction.md
Labels: Accepted, Linguistic Suggestion

#732 Update functions-create-cosmos-db-triggered-function.md
  articles/azure-functions/functions-create-cosmos-db-triggered-function.md
Labels: Accepted, Linguistic Suggestion

#734 Update language-support.md
  articles/cognitive-services/text-analytics/language-support.md
Labels: Accepted, Linguistic Suggestion

#735 Update text-analytics-how-to-entity-linking.md
  articles/cognitive-services/text-analytics/how-tos/text-analytics-how-to-entity-linking.md
Labels: Linguistic Suggestion, Partially Accepted

#736 Update quickstart-create-databricks-workspace-vnet-injection.md
  articles/azure-databricks/quickstart-create-databricks-workspace-vnet-injection.md
Labels: Accepted, Linguistic Suggestion

#721 Update overview.md
  articles/cognitive-services/text-analytics/overview.md
Labels: Accepted, Linguistic Suggestion

#750 Fix mistranslation
  articles/logic-apps/logic-apps-track-integration-account-x12-tracking-schema.md
Labels: In Progress

#751 Fix mistranslation
  articles/managed-applications/create-uidefinition-elements.md
Labels: In Progress

#752 Fix mistranslation
  articles/media-services/previous/media-services-motion-detection.md
Labels: In Progress

#753 Fix mistranslation
  articles/service-fabric/service-fabric-sfctl-application.md
Labels: In Progress

#754 Fix mistranslation
  articles/virtual-machine-scale-sets/virtual-machine-scale-sets-health-extension.md
Labels: In Progress

#720 Update move-your-project-to-azure.md
  articles/cognitive-services/Custom-Vision-Service/move-your-project-to-azure.md
Labels: Accepted, Linguistic Suggestion

#722 Update tutorial-power-bi-key-phrases.md
  articles/cognitive-services/text-analytics/tutorials/tutorial-power-bi-key-phrases.md
Labels: Accepted, Linguistic Suggestion

#723 Update update-application-to-3.0-sdk.md
  articles/cognitive-services/Custom-Vision-Service/update-application-to-3.0-sdk.md
Labels: Accepted, Linguistic Suggestion

#763 Fix mistranslation
  articles/virtual-machines/extensions/agent-dependency-windows.md
Labels: In Progress

#762 Fix mistranslation
  articles/virtual-machines/extensions/agent-dependency-linux.md
Labels: In Progress

#761 Fix mistranslation
  articles/service-fabric/service-fabric-cluster-nodetypes.md
Labels: In Progress

#760 Fix mistranslation
  articles/blockchain/workbench/messages-overview.md
Labels: In Progress

#742 Update speech-to-text.md
  articles/cognitive-services/Speech-Service/speech-to-text.md
Labels: Accepted, Linguistic Suggestion

#743 Update text-analytics-how-to-install-containers.md
  articles/cognitive-services/text-analytics/how-tos/text-analytics-how-to-install-containers.md
Labels: Accepted, Linguistic Suggestion

#744 Update text-analytics-resource-container-config.md
  articles/cognitive-services/text-analytics/text-analytics-resource-container-config.md
Labels: Accepted, Linguistic Suggestion

#745 Update databricks-extract-load-sql-data-warehouse.md
  articles/azure-databricks/databricks-extract-load-sql-data-warehouse.md
Labels: Accepted, Linguistic Suggestion

#755 Update concepts-clusters-workloads.md
  articles/aks/concepts-clusters-workloads.md
Labels: Accepted, Linguistic Suggestion

#758 Update connect-databricks-excel-python-r.md
  articles/azure-databricks/connect-databricks-excel-python-r.md
Labels: Accepted, Linguistic Suggestion

#771 Fix mistranslation
  articles/virtual-machines/extensions/azure-disk-enc-windows.md
Labels: In Progress

#770 Fix mistranslation
  articles/virtual-machines/extensions/azure-disk-enc-linux.md
Labels: In Progress

#772 Fix mistranslation
  articles/virtual-machines/extensions/chef.md
Labels: In Progress

#773 Fix mistranslation
  articles/virtual-machines/extensions/custom-script-linux.md
Labels: In Progress

#756 Update vnet-injection-sql-server.md
  articles/azure-databricks/vnet-injection-sql-server.md
Labels: Accepted, Linguistic Suggestion

#757 Update vnet-injection.md
  articles/azure-databricks/vnet-injection.md
Labels: Accepted, Linguistic Suggestion

#776 Fix mistranslation
  articles/virtual-machines/extensions/custom-script-linuxOstc.md
Labels: Accepted

#781 Fix mistranslation
  articles/virtual-machines/extensions/hpccompute-gpu-linux.md
Labels: Accepted, Linguistic Suggestion

#780 Fix mistranslation
  articles/virtual-machines/extensions/dsc-windows.md
Labels: Accepted, Linguistic Suggestion

#779 Fix mistranslation
  articles/virtual-machines/extensions/dsc-template.md
Labels: Accepted, Linguistic Suggestion

#777 Fix mistranslation
  articles/virtual-machines/extensions/custom-script-windows.md
Labels: Accepted, Linguistic Suggestion

#765 Update concepts-clusters-workloads.md
  articles/aks/concepts-clusters-workloads.md
Labels: Accepted, Linguistic Suggestion

#778 Update cognitive-services-speech-service-rest-auth.md
  includes/cognitive-services-speech-service-rest-auth.md
Labels: Accepted, Linguistic Suggestion

#767 Update quickstart-csharp-dotnetcore-windows.md
  articles/cognitive-services/Speech-Service/quickstart-csharp-dotnetcore-windows.md
Labels: Accepted, Linguistic Suggestion

#787 Fix mistranslation
  articles/virtual-machines/extensions/network-watcher-linux.md
Labels: In Progress

#786 Fix mistranslation
  articles/virtual-machines/extensions/hpccompute-gpu-windows.md
Labels: In Progress

#792 Fix mistranslation
  articles/cognitive-services/Speech/API-Reference-REST/BingVoiceOutput.md
Labels: In Progress

#791 Fix mistranslation
  includes/data-factory-structure-for-rectangualr-datasets.md
Labels: In Progress

#790 Fix mistranslation
  articles/virtual-machines/extensions/oms-windows.md
Labels: In Progress

#789 Fix mistranslation
  articles/virtual-machines/extensions/oms-linux.md
Labels: In Progress

#788 Fix mistranslation
  articles/virtual-machines/extensions/network-watcher-windows.md
Labels: In Progress

#766 Update frequently-asked-questions-databricks.md
  articles/azure-databricks/frequently-asked-questions-databricks.md
Labels: Accepted, Linguistic Suggestion

#768 Update quickstart-java-jre.md
  articles/cognitive-services/Speech-Service/quickstart-java-jre.md
Labels: Accepted, Linguistic Suggestion

#774 Update concepts-clusters-workloads.md
  articles/aks/concepts-clusters-workloads.md
Labels: Accepted, Linguistic Suggestion

#799 Fix mistranslation
  articles/azure-resource-manager/resource-group-template-functions-array.md
Labels: In Progress

#798 Fix mistranslation
  articles/analysis-services/analysis-services-async-refresh.md
Labels: In Progress

#806 Fix mistranslation
  articles/governance/blueprints/reference/blueprint-functions.md
Labels: In Progress

#801 Fix mistranslation
  articles/azure-resource-manager/resource-group-template-functions-deployment.md
Labels: In Progress

#804 Fix mistranslation
  articles/data-factory/concepts-pipelines-activities.md
Labels: In Progress

#805 Fix mistranslation
  articles/data-factory/control-flow-if-condition-activity.md
Labels: In Progress

#782 Update sql-reference-data.md
  articles/stream-analytics/sql-reference-data.md
Labels: Accepted, Linguistic Suggestion

#783 Update stream-analytics-with-azure-functions.md
  articles/stream-analytics/stream-analytics-with-azure-functions.md
Labels: Accepted, Linguistic Suggestion

#784 Update cognitive-services-speech-service-endpoints-text-to-speech.md
  includes/cognitive-services-speech-service-endpoints-text-to-speech.md
Labels: Accepted, Linguistic Suggestion

#785 Update rest-text-to-speech.md
  articles/cognitive-services/Speech-Service/rest-text-to-speech.md
Labels: Accepted, Linguistic Suggestion

#793 Update concepts-clusters-workloads.md
  articles/aks/concepts-clusters-workloads.md
Labels: Accepted, Linguistic Suggestion

#817 Fix mistranslation
  articles/logic-apps/logic-apps-workflow-actions-triggers.md
Labels: Accepted

#818 Fix mistranslation
  articles/logic-apps/logic-apps-workflow-definition-language.md
Labels: Accepted, Linguistic Suggestion

#797 Update voice-first-virtual-assistants.md
  articles/cognitive-services/Speech-Service/voice-first-virtual-assistants.md
Labels: Accepted, Linguistic Suggestion

#824 Fix mistranslation
  articles/media-services/latest/media-services-event-schemas.md
Labels: Accepted

#802 Update text-to-speech.md
  articles/cognitive-services/Speech-Service/text-to-speech.md
Labels: Accepted, Linguistic Suggestion

#803 Update speech-translation.md
  articles/cognitive-services/Speech-Service/speech-translation.md
Labels: Accepted, Linguistic Suggestion

#807 Update tutorial-kubernetes-app-update.md
  articles/aks/tutorial-kubernetes-app-update.md
Labels: Accepted, Linguistic Suggestion

#829 Fix mistranslation
  articles/active-directory/conditional-access/technical-reference.md
Labels: Accepted

#830 Fix mistranslation
  articles/automation/automation-graphical-authoring-intro.md
Labels: Accepted

#808 Update speech-container-configuration.md
  articles/cognitive-services/Speech-Service/speech-container-configuration.md
Labels: Accepted, Linguistic Suggestion

#834 Fix mistranslation
  articles/azure-monitor/insights/solutions-resources-searches-alerts.md
Labels: Accepted

#833 Fix mistranslation
  articles/azure-cache-for-redis/cache-howto-manage-redis-cache-powershell.md
Labels: Accepted, Linguistic Suggestion

#836 Fix mistranslation
  articles/azure-monitor/insights/solutions-solution-file.md
Labels: Accepted, Linguistic Suggestion

#809 Update batch-transcription.md
  articles/cognitive-services/Speech-Service/batch-transcription.md
Labels: Accepted, Linguistic Suggestion

#810 Update how-to-use-codec-compressed-audio-input-streams.md
  articles/cognitive-services/Speech-Service/how-to-use-codec-compressed-audio-input-streams.md
Labels: Accepted, Linguistic Suggestion

#811 Update how-to-use-logging.md
  articles/cognitive-services/Speech-Service/how-to-use-logging.md
Labels: Accepted, Linguistic Suggestion

#816 Update rest-speech-to-text.md
  articles/cognitive-services/Speech-Service/rest-speech-to-text.md
Labels: Accepted, Linguistic Suggestion

#815 Update language-support.md
  articles/cognitive-services/Speech-Service/language-support.md
Labels: Accepted, Linguistic Suggestion

#822 Update how-to-phrase-lists.md
  articles/cognitive-services/Speech-Service/how-to-phrase-lists.md
Labels: Accepted, Linguistic Suggestion

#821 Update regions.md
  articles/cognitive-services/Speech-Service/regions.md
Labels: Accepted, Linguistic Suggestion
