Repository MicrosoftDocs/azure-docs.ko-kr, pull requests merged in 2019-02, with the labels that each got.

#315 Update unnatural korean contexts in this doc.
  includes/storage-common-redundancy-lrs.md
Labels: Accepted With Changes, Linguistic Suggestion

#316 Update this article with the correct Korean context
  articles/storage/common/storage-redundancy-grs.md
Labels: Accepted With Changes, Linguistic Suggestion

#317 Fix wrong korean words.
  articles/cdn/cdn-pop-locations.md
Labels: Linguistic Suggestion, Partially Accepted

#321 Fix missing
  articles/storage/blobs/data-lake-storage-quickstart-create-databricks-account.md
Labels: Accepted, Linguistic Suggestion
