Repository MicrosoftDocs/azure-docs.ko-kr, pull requests merged in 2019-01, with the labels that each got.

#275 Translation translation omission
  articles/data-factory/concepts-pipelines-activities.md
Labels: Accepted, Linguistic Suggestion, Source Issue

#277 Translation translation omission
  articles/azure-functions/functions-bindings-cosmosdb-v2.md
Labels: Accepted, Technical Issue

#276 Translation translation omission
  articles/data-factory/v1/data-factory-create-pipelines.md
Labels: Accepted, Technical Issue

#282 Fix typo
  articles/active-directory-b2c/active-directory-b2c-custom-rest-api-netfw.md
Labels: Accepted, Technical Issue

#288 Fix typo
  articles/azure-functions/functions-bindings-microsoft-graph.md
Labels: Accepted, Linguistic Suggestion

#286 Fix typo
  articles/app-service/containers/tutorial-auth-aad.md
Labels: Accepted, Linguistic Suggestion

#284 Fix typo
  articles/app-service/app-service-web-tutorial-auth-aad.md
Labels: Accepted, Linguistic Suggestion

#283 Fix typo
  articles/active-directory/develop/v2-permissions-and-consent.md
Labels: Accepted, Linguistic Suggestion

#300 Fix missing
  articles/cognitive-services/Custom-Vision-Service/csharp-tutorial-od.md
Labels: Accepted, Linguistic Suggestion

#293 Fix missing
  articles/azure-maps/extend-geojson.md
Labels: Accepted, Linguistic Suggestion

#299 Fix missing
  articles/cognitive-services/Content-Moderator/ecommerce-retail-catalog-moderation.md
Labels: Accepted, Linguistic Suggestion

#270 Update active-directory-whatis.md
  articles/active-directory/fundamentals/active-directory-whatis.md
Labels: Linguistic Suggestion

#292 Fix missing
  articles/azure-maps/consumption-model.md
Labels: Accepted, Linguistic Suggestion

#305 Fix missing
  articles/storage/blobs/data-lake-storage-quickstart-create-databricks-account.md
Labels: Accepted, Technical Issue

#306 Fix missing
  articles/logic-apps/logic-apps-create-variables-store-values.md
Labels: Accepted, Linguistic Suggestion

#304 Fix missing
  articles/cognitive-services/LUIS/luis-container-configuration.md
Labels: Accepted, Linguistic Suggestion

#308 Fix missing
  articles/data-factory/connector-odata.md
Labels: Accepted, Linguistic Suggestion
