Repository MicrosoftDocs/azure-docs.ko-kr, pull requests merged in 2019-05, with the labels that each got.

#364 Update sql-database-auditing.md
  articles/sql-database/sql-database-auditing.md
Labels: Linguistic Suggestion, Partially Accepted

#365 Update sql-database-data-discovery-and-classification.md
  articles/sql-database/sql-database-data-discovery-and-classification.md
Labels: Linguistic Suggestion, Partially Accepted

#367 Update sql-data-warehouse-memory-optimizations-for-columnstore-compre…
  articles/sql-data-warehouse/sql-data-warehouse-memory-optimizations-for-columnstore-compression.md
Labels: Accepted, Linguistic Suggestion

#374 Update sql-data-warehouse-tables-overview.md
  articles/sql-data-warehouse/sql-data-warehouse-tables-overview.md
Labels: Accepted, Linguistic Suggestion

#375 Update sql-data-warehouse-develop-ctas.md
  articles/sql-data-warehouse/sql-data-warehouse-develop-ctas.md
Labels: Accepted, Linguistic Suggestion

#376 Update sql-data-warehouse-tables-index.md
  articles/sql-data-warehouse/sql-data-warehouse-tables-index.md
Labels: Accepted, Linguistic Suggestion

#377 Update sql-data-warehouse-tables-identity.md
  articles/sql-data-warehouse/sql-data-warehouse-tables-identity.md
Labels: Accepted, Linguistic Suggestion

#378 Update sql-data-warehouse-tables-partition.md
  articles/sql-data-warehouse/sql-data-warehouse-tables-partition.md
Labels: Accepted, Linguistic Suggestion

#379 Update design-guidance-for-replicated-tables.md
  articles/sql-data-warehouse/design-guidance-for-replicated-tables.md
Labels: Accepted, Linguistic Suggestion

#381 Update sql-data-warehouse-tables-statistics.md
  articles/sql-data-warehouse/sql-data-warehouse-tables-statistics.md
Labels: Accepted, Linguistic Suggestion

#384 Update sql-data-warehouse-develop-loops.md
  articles/sql-data-warehouse/sql-data-warehouse-develop-loops.md
Labels: Linguistic Suggestion, Partially Accepted

#383 Update sql-data-warehouse-tables-temporary.md
  articles/sql-data-warehouse/sql-data-warehouse-tables-temporary.md
Labels: Accepted, Linguistic Suggestion

#385 Update sql-data-warehouse-develop-stored-procedures.md
  articles/sql-data-warehouse/sql-data-warehouse-develop-stored-procedures.md
Labels: Accepted, Linguistic Suggestion

#389 Update resource-classes-for-workload-management.md
  articles/sql-data-warehouse/resource-classes-for-workload-management.md
Labels: Accepted, Linguistic Suggestion

#390 Update sql-data-warehouse-workload-classification.md
  articles/sql-data-warehouse/sql-data-warehouse-workload-classification.md
Labels: Accepted, Linguistic Suggestion

#414 Fix mistranslation
  articles/azure-functions/functions-host-json.md
Labels: Accepted, In Progress

#423 Update app-service-web-get-started-dotnet.md
  articles/app-service/app-service-web-get-started-dotnet.md
Labels: In Progress

#391 Update sql-data-warehouse-workload-importance.md
  articles/sql-data-warehouse/sql-data-warehouse-workload-importance.md
Labels: Accepted, Linguistic Suggestion

#394 Update maintenance-scheduling.md
  articles/sql-data-warehouse/maintenance-scheduling.md
Labels: Accepted, Linguistic Suggestion

#433 Fix mistranslation
  articles/data-factory/connector-amazon-marketplace-web-service.md
Labels: Accepted, In Progress

#435 Fix mistranslation
  articles/data-factory/connector-amazon-simple-storage-service.md
Labels: Accepted, In Progress

#432 Fix mistranslation
  articles/billing/billing-review-subscription-billing.md
Labels: Accepted, In Progress

#436 Fix mistranslation
  articles/data-factory/connector-azure-blob-storage.md
Labels: Accepted, In Progress

#437 Fix mistranslation
  articles/data-factory/connector-azure-cosmos-db-mongodb-api.md
Labels: Accepted, In Progress

#438 Fix mistranslation
  articles/data-factory/connector-azure-cosmos-db.md
Labels: Accepted, In Progress

#439 Fix mistranslation
  articles/data-factory/connector-azure-data-explorer.md
Labels: Accepted, In Progress

#441 Fix mistranslation
  articles/data-factory/connector-azure-data-lake-store.md
Labels: In Progress

#440 Fix mistranslation
  articles/data-factory/connector-azure-data-lake-storage.md
Labels: Accepted, In Progress

#442 Fix mistranslation
  articles/data-factory/connector-azure-database-for-mariadb.md
Labels: Accepted, In Progress

#443 Fix mistranslation
  articles/data-factory/connector-azure-database-for-mysql.md
Labels: Accepted, In Progress

#366 Update guidance-for-loading-data.md
  articles/sql-data-warehouse/guidance-for-loading-data.md
Labels: Accepted, Linguistic Suggestion

#396 Update changing-maintenance-schedule.md
  articles/sql-data-warehouse/changing-maintenance-schedule.md
Labels: Linguistic Suggestion, Partially Accepted

#398 Update sql-database-conditional-access.md
  articles/sql-database/sql-database-conditional-access.md
Labels: Linguistic Suggestion, Partially Accepted

#449 Fix mistranslation
  articles/data-factory/connector-azure-database-for-postgresql.md
Labels: Accepted, In Progress

#450 Fix mistranslation
  articles/data-factory/connector-azure-file-storage.md
Labels: Accepted, In Progress

#402 Update load-data-from-azure-blob-storage-using-polybase.md
  articles/sql-data-warehouse/load-data-from-azure-blob-storage-using-polybase.md
Labels: Accepted, Linguistic Suggestion

#404 Update sql-data-warehouse-load-from-azure-blob-storage-with-polybase.md
  articles/sql-data-warehouse/sql-data-warehouse-load-from-azure-blob-storage-with-polybase.md
Labels: Accepted, Linguistic Suggestion

#405 Update sql-data-warehouse-load-from-azure-data-lake-store.md
  articles/sql-data-warehouse/sql-data-warehouse-load-from-azure-data-lake-store.md
Labels: Accepted, Linguistic Suggestion

#456 Fix mistranslation
  articles/data-factory/connector-concur.md
Labels: Accepted, In Progress

#458 Fix mistranslation
  articles/data-factory/connector-db2.md
Labels: Accepted, In Progress

#459 Fix mistranslation
  articles/data-factory/connector-drill.md
Labels: Accepted, In Progress

#460 Fix mistranslation
  articles/data-factory/connector-dynamics-ax.md
Labels: Accepted, In Progress

#461 Fix mistranslation
  articles/data-factory/connector-dynamics-crm-office-365.md
Labels: Accepted, In Progress

#462 Fix mistranslation
  articles/data-factory/connector-file-system.md
Labels: Accepted, In Progress

#463 Fix mistranslation
  articles/data-factory/connector-ftp.md
Labels: Accepted, In Progress

#406 Update databricks-extract-load-sql-data-warehouse.md
  articles/azure-databricks/databricks-extract-load-sql-data-warehouse.md
Labels: Accepted, Linguistic Suggestion

#407 Update load-azure-sql-data-warehouse.md
  articles/data-factory/load-azure-sql-data-warehouse.md
Labels: Linguistic Suggestion, Partially Accepted

#408 Update sql-data-warehouse-query-ssms.md
  articles/sql-data-warehouse/sql-data-warehouse-query-ssms.md
Labels: Accepted, Linguistic Suggestion

#410 Update load-data-wideworldimportersdw.md
  articles/sql-data-warehouse/load-data-wideworldimportersdw.md
Labels: Accepted, Linguistic Suggestion

#411 Update sql-data-warehouse-query-visual-studio.md
  articles/sql-data-warehouse/sql-data-warehouse-query-visual-studio.md
Labels: Accepted, Linguistic Suggestion

#412 Update sql-data-warehouse-install-visual-studio.md
  articles/sql-data-warehouse/sql-data-warehouse-install-visual-studio.md
Labels: Accepted, Linguistic Suggestion

#413 Update analyze-your-workload.md
  articles/sql-data-warehouse/analyze-your-workload.md
Labels: Accepted, Linguistic Suggestion

#469 Fix mistranslation
  articles/data-factory/connector-google-adwords.md
Labels: Accepted, In Progress

#472 Fix mistranslation
  articles/data-factory/connector-hbase.md
Labels: Accepted, In Progress

#471 Fix mistranslation
  articles/data-factory/connector-greenplum.md
Labels: Accepted, In Progress

#415 Update upgrade-to-latest-generation.md
  articles/sql-data-warehouse/upgrade-to-latest-generation.md
Labels: Linguistic Suggestion, Partially Accepted

#416 Update sql-data-warehouse-restore.md
  articles/sql-data-warehouse/sql-data-warehouse-restore.md
Labels: Accepted, Linguistic Suggestion

#417 Update sql-data-warehouse-monitor-workload-portal.md
  articles/sql-data-warehouse/sql-data-warehouse-monitor-workload-portal.md
Labels: Accepted, Linguistic Suggestion

#418 Update sql-data-warehouse-manage-monitor.md
  articles/sql-data-warehouse/sql-data-warehouse-manage-monitor.md
Labels: Accepted, Linguistic Suggestion

#419 Update sql-data-warehouse-get-started-analyze-with-azure-machine-lear…
  articles/sql-data-warehouse/sql-data-warehouse-get-started-analyze-with-azure-machine-learning.md
Labels: Linguistic Suggestion, Partially Accepted

#420 Update fivetran-quickstart.md
  articles/sql-data-warehouse/fivetran-quickstart.md
Labels: Accepted, Linguistic Suggestion

#421 Update striim-quickstart.md
  articles/sql-data-warehouse/striim-quickstart.md
Labels: Accepted, Linguistic Suggestion

#422 Update sql-data-warehouse-integrate-azure-stream-analytics.md
  articles/sql-data-warehouse/sql-data-warehouse-integrate-azure-stream-analytics.md
Labels: Accepted, Linguistic Suggestion

#424 Update concepts-collector.md
  articles/migrate/concepts-collector.md
Labels: Accepted, Linguistic Suggestion

#494 Fix mistranslation
  articles/data-factory/connector-hdfs.md
Labels: Accepted, In Progress

#495 Fix mistranslation
  articles/data-factory/connector-hive.md
Labels: Accepted, In Progress

#496 Fix mistranslation
  articles/data-factory/connector-http.md
Labels: Accepted, In Progress

#497 Fix mistranslation
  articles/data-factory/connector-hubspot.md
Labels: Accepted, In Progress

#500 Fix mistranslation
  articles/data-factory/connector-magento.md
Labels: Accepted, In Progress

#498 Fix mistranslation
  articles/data-factory/connector-impala.md
Labels: Accepted, In Progress

#502 Fix mistranslation
  articles/data-factory/connector-marketo.md
Labels: Accepted, In Progress

#503 Fix mistranslation
  articles/data-factory/connector-mongodb-legacy.md
Labels: Accepted, In Progress

#499 Fix mistranslation
  articles/data-factory/connector-jira.md
Labels: Accepted, In Progress

#501 Fix mistranslation
  articles/data-factory/connector-mariadb.md
Labels: Accepted, In Progress

#487 Update how-to-migrate-at-scale.md
  articles/migrate/how-to-migrate-at-scale.md
Labels: In Progress

#427 Update sql-data-warehouse-troubleshoot-connectivity.md
  articles/sql-data-warehouse/sql-data-warehouse-troubleshoot-connectivity.md
Labels: Accepted, Linguistic Suggestion

#429 Update sql-data-warehouse-reference-powershell-cmdlets.md
  articles/sql-data-warehouse/sql-data-warehouse-reference-powershell-cmdlets.md
Labels: Accepted, Linguistic Suggestion

#513 Fix mistranslation
  articles/data-factory/connector-mongodb.md
Labels: Accepted, In Progress

#514 Fix mistranslation
  articles/data-factory/connector-mysql.md
Labels: Accepted, In Progress

#515 Fix mistranslation
  articles/data-factory/connector-netezza.md
Labels: Accepted, In Progress

#516 Fix mistranslation
  articles/data-factory/connector-odata.md
Labels: Accepted, In Progress

#517 Fix mistranslation
  articles/data-factory/connector-odbc.md
Labels: Accepted, In Progress

#521 Fix mistranslation
  articles/data-factory/connector-oracle.md
Labels: Accepted, In Progress

#518 Fix mistranslation
  articles/data-factory/connector-oracle-eloqua.md
Labels: Accepted, In Progress

#519 Fix mistranslation
  articles/data-factory/connector-oracle-responsys.md
Labels: Accepted, In Progress

#520 Fix mistranslation
  articles/data-factory/connector-oracle-service-cloud.md
Labels: Accepted, In Progress

#447 Update face-detection.md
  articles/cognitive-services/Face/concepts/face-detection.md
Labels: Accepted, Linguistic Suggestion

#448 Update face-recognition.md
  articles/cognitive-services/Face/concepts/face-recognition.md
Labels: Accepted, Linguistic Suggestion

#493 Update cognitive-services-containers-run-multiple-same-host.md
  includes/cognitive-services-containers-run-multiple-same-host.md
Labels: Accepted, Linguistic Suggestion

#492 Update cognitive-services-containers-host-computer.md
  includes/cognitive-services-containers-host-computer.md
Labels: Accepted, Linguistic Suggestion

#452 Update concepts-dependency-visualization.md
  articles/migrate/concepts-dependency-visualization.md
Labels: Accepted, Linguistic Suggestion

#485 Update how-to-migrate-face-data.md
  articles/cognitive-services/Face/Face-API-How-to-Topics/how-to-migrate-face-data.md
Labels: Accepted, Linguistic Suggestion

#484 Update how-to-use-large-scale.md
  articles/cognitive-services/Face/Face-API-How-to-Topics/how-to-use-large-scale.md
Labels: Accepted, Linguistic Suggestion

#483 Update concepts-server-logs.md
  articles/mysql/concepts-server-logs.md
Labels: Accepted, Linguistic Suggestion

#482 Update concepts-data-access-and-security-vnet.md
  articles/mysql/concepts-data-access-and-security-vnet.md
Labels: Linguistic Suggestion, Partially Accepted

#479 Update concepts-data-access-and-security-threat-protection.md
  articles/mysql/concepts-data-access-and-security-threat-protection.md
Labels: Accepted, Linguistic Suggestion

#477 Update concepts-supported-versions.md
  articles/mysql/concepts-supported-versions.md
Labels: Accepted, Linguistic Suggestion

#476 Update migrate-best-practices-costs.md
  articles/migrate/migrate-best-practices-costs.md
Labels: Accepted, Linguistic Suggestion

#468 Update concepts-servers.md
  articles/mysql/concepts-servers.md
Labels: Accepted, Linguistic Suggestion

#465 Update how-to-use-headpose.md
  articles/cognitive-services/Face/Face-API-How-to-Topics/how-to-use-headpose.md
Labels: Accepted, Linguistic Suggestion

#455 Update sql-api-dotnet-application.md
  articles/cosmos-db/sql-api-dotnet-application.md
Labels: Accepted, Linguistic Suggestion

#454 Update overview.md
  articles/mysql/overview.md
Labels: Accepted, Linguistic Suggestion

#453 Update HowtoDetectFacesinImage.md
  articles/cognitive-services/Face/Face-API-How-to-Topics/HowtoDetectFacesinImage.md
Labels: Accepted, Linguistic Suggestion

#527 Fix mistranslation
  articles/data-factory/connector-paypal.md
Labels: Accepted, In Progress

#534 Fix mistranslation
  articles/data-factory/connector-salesforce-marketing-cloud.md
Labels: Accepted, In Progress

#528 Fix mistranslation
  articles/data-factory/connector-phoenix.md
Labels: Accepted, In Progress

#529 Fix mistranslation
  articles/data-factory/connector-postgresql.md
Labels: Accepted, In Progress

#532 Fix mistranslation
  articles/data-factory/connector-rest.md
Labels: Accepted, In Progress

#531 Fix mistranslation
  articles/data-factory/connector-quickbooks.md
Labels: Accepted, In Progress

#530 Fix mistranslation
  articles/data-factory/connector-presto.md
Labels: Accepted, In Progress

#541 Fix mistranslation
  articles/data-factory/connector-salesforce.md
Labels: Accepted, In Progress

#486 Update how-to-create-group-dependencies.md
  articles/migrate/how-to-create-group-dependencies.md
Labels: Accepted, Linguistic Suggestion

#480 Update specify-recognition-model.md
  articles/cognitive-services/Face/Face-API-How-to-Topics/specify-recognition-model.md
Labels: Accepted, Linguistic Suggestion

#481 Update how-to-scale-assessment.md
  articles/migrate/how-to-scale-assessment.md
Labels: Accepted, Linguistic Suggestion

#546 Fix mistranslation
  articles/data-factory/connector-sap-business-warehouse-open-hub.md
Labels: Accepted, In Progress

#547 Fix mistranslation
  articles/data-factory/connector-sap-business-warehouse.md
Labels: Accepted, In Progress

#548 Fix mistranslation
  articles/data-factory/connector-sap-cloud-for-customer.md
Labels: Accepted, In Progress

#549 Fix mistranslation
  articles/data-factory/connector-sap-ecc.md
Labels: Accepted, In Progress

#552 Fix mistranslation
  articles/data-factory/connector-sftp.md
Labels: Accepted, In Progress

#550 Fix mistranslation
  articles/data-factory/connector-sap-hana.md
Labels: Accepted, In Progress

#551 Fix mistranslation
  articles/data-factory/connector-servicenow.md
Labels: Accepted, In Progress

#489 Update concepts-compatibility.md
  articles/mysql/concepts-compatibility.md
Labels: Accepted, Linguistic Suggestion

#490 Update concepts-read-replicas.md
  articles/mysql/concepts-read-replicas.md
Labels: Accepted, Linguistic Suggestion

#491 Update face-how-to-install-containers.md
  articles/cognitive-services/Face/face-how-to-install-containers.md
Labels: Accepted, Linguistic Suggestion

#504 Update how-to-create-group-machine-dependencies.md
  articles/migrate/how-to-create-group-machine-dependencies.md
Labels: Accepted, Linguistic Suggestion

#505 Update how-to-create-group-dependencies.md
  articles/migrate/how-to-create-group-dependencies.md
Labels: Accepted, Linguistic Suggestion

#507 Update resources-faq.md
  articles/migrate/resources-faq.md
Labels: Accepted, Linguistic Suggestion

#508 Update troubleshooting-general.md
  articles/migrate/troubleshooting-general.md
Labels: Accepted, Linguistic Suggestion

#509 Update cognitive-services-containers-api-documentation.md
  includes/cognitive-services-containers-api-documentation.md
Labels: Linguistic Suggestion, Partially Accepted

#510 Update cognitive-services-containers-how-to-billing-info.md
  includes/cognitive-services-containers-how-to-billing-info.md
Labels: Accepted, Linguistic Suggestion

#511 Update cognitive-services-containers-configuration-shared-settings-ta…
  includes/cognitive-services-containers-configuration-shared-settings-table.md
Labels: Accepted, Linguistic Suggestion

#512 Update cognitive-services-containers-configuration-shared-settings-ap…
  includes/cognitive-services-containers-configuration-shared-settings-application-insights.md
Labels: Accepted, Linguistic Suggestion

#526 Update vs-face-connected-service.md
  articles/cognitive-services/Face/vs-face-connected-service.md
Labels: Accepted, Linguistic Suggestion

#524 Update cognitive-services-containers-configuration-shared-settings-lo…
  includes/cognitive-services-containers-configuration-shared-settings-logging.md
Labels: Accepted, Linguistic Suggestion

#525 Update face-resource-container-config.md
  articles/cognitive-services/Face/face-resource-container-config.md
Labels: Accepted, Linguistic Suggestion

#539 Update quickstart-create-server-database-portal.md
  articles/postgresql/quickstart-create-server-database-portal.md
Labels: Accepted, Linguistic Suggestion

#540 Update concepts-firewall-rules.md
  articles/postgresql/concepts-firewall-rules.md
Labels: Accepted, Linguistic Suggestion

#533 Update howto-create-manage-server-portal.md
  articles/mysql/howto-create-manage-server-portal.md
Labels: Accepted, Linguistic Suggestion

#542 Update concepts-extensions.md
  articles/postgresql/concepts-extensions.md
Labels: Accepted, Linguistic Suggestion

#545 Update concepts-ssl-connection-security.md
  articles/postgresql/concepts-ssl-connection-security.md
Labels: Accepted, Linguistic Suggestion

#544 Update concepts-pricing-tiers.md
  articles/postgresql/concepts-pricing-tiers.md
Labels: Accepted, Linguistic Suggestion

#543 Update concepts-limits.md
  articles/postgresql/concepts-limits.md
Labels: Accepted, Linguistic Suggestion

#553 Update contoso-migration-assessment.md
  articles/migrate/contoso-migration-assessment.md
Labels: Accepted, Linguistic Suggestion

#535 Update resources-faq.md
  articles/migrate/resources-faq.md
Labels: Accepted, Linguistic Suggestion

#536 Update contoso-migration-infrastructure.md
  articles/migrate/contoso-migration-infrastructure.md
Labels: Accepted, Linguistic Suggestion

#538 Update concepts-servers.md
  articles/postgresql/concepts-servers.md
Labels: Accepted, Linguistic Suggestion

#522 문서 수정
  articles/iot-edge/how-to-install-iot-edge-windows-with-linux.md
Labels: Accepted, Linguistic Suggestion

#523 Update resources-faq.md
  articles/migrate/resources-faq.md
Labels: Accepted, Linguistic Suggestion

#537 Update quickstart-create-server-database-portal.md
  articles/postgresql/quickstart-create-server-database-portal.md
Labels: Linguistic Suggestion, Partially Accepted

#565 Update contoso-migration-rehost-vm-sql-ag.md
  articles/migrate/contoso-migration-rehost-vm-sql-ag.md
Labels: In Progress
