Repository MicrosoftDocs/azure-docs.ko-kr, pull requests merged in 2019-04, with the labels that each got.

#336 Update virtual-machines-windows-sql-high-availability-dr.md
  articles/virtual-machines/windows/sql/virtual-machines-windows-sql-high-availability-dr.md
Labels: In Progress

#331 Update iot-edge-runtime.md
  articles/iot-edge/iot-edge-runtime.md
Labels: Accepted, Linguistic Suggestion

#332 match button label text as same as its page title
  articles/app-service/app-service-web-get-started-dotnet.md
Labels: Accepted, Linguistic Suggestion

#333 improve translation quality
  articles/app-service/app-service-web-get-started-dotnet.md
Labels: Accepted, Linguistic Suggestion

#334 change '기계 학습' 'Machine Learning' to '머신 러닝'
  articles/machine-learning/service/overview-what-is-azure-ml.md
Labels: Linguistic Suggestion, Partially Accepted

#335 fix translation to a finished sentence
  articles/machine-learning/service/tutorial-train-models-with-aml.md
Labels: Accepted, Linguistic Suggestion

#341 Fix mistranslation
  articles/azure-monitor/platform/api-alerts.md
Labels: Accepted, In Progress

#339 Fix mistranslation
  articles/data-factory/v1/data-factory-azure-sql-data-warehouse-connector.md
Labels: Accepted, In Progress

#338 Fix mistranslation
  articles/data-factory/v1/data-factory-azure-table-connector.md
Labels: Accepted, In Progress

#337 Fix mistranslation
  articles/data-factory/connector-azure-sql-data-warehouse.md
Labels: Accepted, In Progress

#345 Fix mistranslation
  articles/data-factory/connector-azure-search.md
Labels: Accepted, In Progress, Linguistic Suggestion

#344 Fix mistranslation
  articles/azure-monitor/platform/archive-diagnostic-logs.md
Labels: Accepted, In Progress, Linguistic Suggestion

#343 Fix mistranslation
  articles/data-factory/connector-sql-server.md
Labels: Accepted, In Progress, Linguistic Suggestion

#342 Fix mistranslation
  articles/data-factory/v1/data-factory-azure-sql-connector.md
Labels: Accepted, In Progress, Linguistic Suggestion

#346 Fix mistranslation
  articles/azure-monitor/insights/wire-data.md
Labels: Accepted, In Progress, Linguistic Suggestion

#347 Fix mistranslation
  articles/azure-monitor/platform/activity-logs-overview.md
Labels: Accepted, In Progress, Linguistic Suggestion

#348 Fix mistranslation
  articles/data-factory/connector-azure-sql-database-managed-insance.md
Labels: Accepted, In Progress, Linguistic Suggestion

#349 Fix mistranslation
  articles/data-factory/connector-azure-sql-database.md
Labels: Accepted, In Progress, Linguistic Suggestion

#352 Fix mistranslation
  articles/connectors/connectors-create-api-bingsearch.md
Labels: Accepted, In Progress

#351 Fix mistranslation
  articles/azure-monitor/insights/solutions-resources-automation.md
Labels: Accepted, In Progress

#354 Fix mistranslation
  articles/azure-maps/geofence-geojson.md
Labels: Accepted, In Progress

#353 Fix mistranslation
  articles/api-management/api-management-product-templates.md
Labels: Accepted, In Progress

#357 Fix mistranslation
  articles/automation/automation-manage-send-joblogs-log-analytics.md
Labels: Accepted, In Progress

#356 Fix mistranslation
  articles/azure-functions/functions-host-json.md
Labels: Accepted, In Progress

#355 Fix mistranslation
  articles/azure-functions/functions-host-json-v1.md
Labels: Accepted, In Progress

#350 sink 설명 개선
  articles/iot-edge/module-composition.md
Labels: Accepted, Linguistic Suggestion

#363 Fix mistranslation
  articles/api-management/api-management-howto-use-azure-monitor.md
Labels: Accepted, In Progress

#361 Fix mistranslation
  articles/automation/automation-dsc-diagnostics.md
Labels: Accepted, In Progress

#360 Fix mistranslation
  articles/data-factory/control-flow-filter-activity.md
Labels: Accepted, In Progress

#373 Fix mistranslation
  articles/data-factory/connector-azure-table-storage.md
Labels: Accepted, In Progress

#372 Fix mistranslation
  articles/azure-monitor/insights/vminsights-log-search.md
Labels: Accepted, In Progress

#371 Fix mistranslation
  articles/data-factory/connector-web-table.md
Labels: Accepted, In Progress

#369 Fix mistranslation
  articles/api-management/api-management-howto-properties.md
Labels: Accepted, In Progress

#368 Fix mistranslation
  articles/api-management/api-management-error-handling-policies.md
Labels: Accepted, In Progress

#382 Fix mistranslation
  articles/azure-functions/functions-bindings-cosmosdb-v2.md
Labels: Accepted, In Progress

#358 Update create-data-warehouse-portal.md
  articles/sql-data-warehouse/create-data-warehouse-portal.md
Labels: Accepted

#359 Update design-elt-data-loading.md
  articles/sql-data-warehouse/design-elt-data-loading.md
Labels: Accepted

#362 Update sql-database-ssms-mfa-authentication.md
  articles/sql-database/sql-database-ssms-mfa-authentication.md
Labels: Accepted, Linguistic Suggestion
