Repository MicrosoftDocs/azure-docs.ko-kr, pull requests merged in 2019-03, with the labels that each got.

#324 Fix typo
  articles/storage/blobs/data-lake-storage-quickstart-create-databricks-account.md
Labels: Accepted, Technical Issue

#327 Update sql-data-warehouse-overview-faq.md
  articles/sql-data-warehouse/sql-data-warehouse-overview-faq.md
Labels: Accepted, Linguistic Suggestion

#326 Update cheat-sheet.md
  articles/sql-data-warehouse/cheat-sheet.md
Labels: In Progress, Linguistic Suggestion

#328 Edit sentence and remove unnecessary word
  articles/machine-learning/service/overview-what-happened-to-workbench.md
Labels: Accepted, Linguistic Suggestion
