Repository MicrosoftDocs/azure-docs.ko-kr, pull requests merged in 2019-07, with the labels that each got.

#849 Fix mistranslation
  articles/azure-monitor/platform/autoscale-webhook-email.md
Labels: Accepted

#826 Update how-to-custom-speech-deploy-model.md
  articles/cognitive-services/Speech-Service/how-to-custom-speech-deploy-model.md
Labels: Accepted, Linguistic Suggestion

#827 Update how-to-custom-speech.md
  articles/cognitive-services/Speech-Service/how-to-custom-speech.md
Labels: Accepted, Linguistic Suggestion

#844 Update stream-analytics-edge-csharp-udf.md
  articles/stream-analytics/stream-analytics-edge-csharp-udf.md
Labels: Accepted, Linguistic Suggestion

#845 Update stream-analytics-javascript-user-defined-functions.md
  articles/stream-analytics/stream-analytics-javascript-user-defined-functions.md
Labels: Accepted, Linguistic Suggestion

#842 Update concepts-network.md
  articles/aks/concepts-network.md
Labels: Accepted, Linguistic Suggestion

#852 Fix mistranslation
  articles/azure-monitor/platform/powershell-quickstart-samples.md
Labels: Accepted

#831 Update concepts-security.md
  articles/aks/concepts-security.md
Labels: Linguistic Suggestion, Partially Accepted

#843 Update concepts-network.md
  articles/aks/concepts-network.md
Labels: Accepted, Linguistic Suggestion

#858 Fix mistranslation
  articles/blockchain/service/send-transaction.md
Labels: Accepted

#859 Fix mistranslation
  articles/blockchain/workbench/configuration.md
Labels: Accepted

#860 Fix mistranslation
  articles/cognitive-services/Speech/API-Reference-REST/websocketprotocol.md
Labels: Accepted, Linguistic Suggestion

#857 Fix mistranslation
  articles/blockchain/service/manage-consortium-powershell.md
Labels: Accepted, Linguistic Suggestion

#848 Update concepts-network.md
  articles/aks/concepts-network.md
Labels: Accepted, Linguistic Suggestion

#847 Update concepts-network.md
  articles/aks/concepts-network.md
Labels: Accepted, Linguistic Suggestion

#846 Update concepts-network.md
  articles/aks/concepts-network.md
Labels: Accepted, Linguistic Suggestion

#866 Fix mistranslation
  articles/data-factory/v1/data-factory-create-datasets.md
Labels: Accepted, Linguistic Suggestion

#865 Fix mistranslation
  articles/data-factory/v1/data-factory-azure-table-connector.md
Labels: Accepted, Linguistic Suggestion

#869 Update overview.md
  articles/app-service/overview.md
Labels: Accepted

#851 Update how-to-custom-speech-test-data.md
  articles/cognitive-services/Speech-Service/how-to-custom-speech-test-data.md
Labels: Accepted, Linguistic Suggestion

#856 Update how-to-custom-speech-evaluate-data.md
  articles/cognitive-services/Speech-Service/how-to-custom-speech-evaluate-data.md
Labels: Accepted, Linguistic Suggestion

#855 Update how-to-custom-speech-inspect-data.md
  articles/cognitive-services/Speech-Service/how-to-custom-speech-inspect-data.md
Labels: Accepted, Linguistic Suggestion

#864 Update support.md
  articles/cognitive-services/Speech-Service/support.md
Labels: Accepted, Linguistic Suggestion

#863 Update how-to-custom-voice.md
  articles/cognitive-services/Speech-Service/how-to-custom-voice.md
Labels: Accepted, Linguistic Suggestion

#862 Update how-to-custom-speech-train-model.md
  articles/cognitive-services/Speech-Service/how-to-custom-speech-train-model.md
Labels: Accepted, Linguistic Suggestion

#874 Fix mistranslation
  articles/hdinsight/domain-joined/apache-domain-joined-create-configure-enterprise-security-cluster.md
Labels: Accepted

#873 Fix typo
  articles/data-factory/v1/data-factory-hive-activity.md
Labels: Accepted

#870 Update concepts-scale.md
  articles/aks/concepts-scale.md
Labels: Accepted, Linguistic Suggestion

#880 Fix mistranslation
  articles/hdinsight/hdinsight-hadoop-customize-cluster-linux.md
Labels: Accepted

#882 Fix mistranslation
  articles/mysql/tutorial-design-database-using-cli.md
Labels: Accepted, Linguistic Suggestion

#883 Fix mistranslation
  articles/postgresql/tutorial-design-database-using-azure-cli.md
Labels: Accepted, Linguistic Suggestion

#877 Update sql-database-single-database-get-started-template.md
  articles/sql-database/sql-database-single-database-get-started-template.md
Labels: Accepted, Linguistic Suggestion

#876 Update sql-database-single-database-get-started.md
  articles/sql-database/sql-database-single-database-get-started.md
Labels: Accepted, Linguistic Suggestion

#878 Update sql-database-connect-query.md
  articles/sql-database/sql-database-connect-query.md
Labels: Accepted, Linguistic Suggestion

#879 Fix mistranslation
  articles/hdinsight/hdinsight-hadoop-create-linux-clusters-adf.md
Labels: Accepted, Linguistic Suggestion

#885 Fix mistranslation
  articles/traffic-manager/traffic-manager-powershell-arm.md
Labels: Accepted

#886 Fix mistranslation
  articles/app-service-mobile/app-service-mobile-ios-get-started-offline-data.md
Labels: Accepted

#888 Fix mistranslation
  articles/azure-functions/functions-bindings-sendgrid.md
Labels: Accepted, Linguistic Suggestion

#887 Fix mistranslation
  articles/azure-cache-for-redis/cache-howto-manage-redis-cache-powershell.md
Labels: Accepted, Linguistic Suggestion

#868 Update how-to-migrate-from-custom-speech-service.md
  articles/cognitive-services/Speech-Service/how-to-migrate-from-custom-speech-service.md
Labels: Accepted, Linguistic Suggestion

#867 Update how-to-migrate-from-bing-speech.md
  articles/cognitive-services/Speech-Service/how-to-migrate-from-bing-speech.md
Labels: Accepted, Linguistic Suggestion

#871 Update how-to-migrate-from-translator-speech-api.md
  articles/cognitive-services/Speech-Service/how-to-migrate-from-translator-speech-api.md
Labels: Accepted, Linguistic Suggestion

#884 Update sql-database-connect-query-dotnet-visual-studio.md
  articles/sql-database/sql-database-connect-query-dotnet-visual-studio.md
Labels: Accepted, Linguistic Suggestion

#889 Update sql-database-connect-query-php.md
  articles/sql-database/sql-database-connect-query-php.md
Labels: Accepted, Linguistic Suggestion

#872 Update speech-container-howto.md
  articles/cognitive-services/Speech-Service/speech-container-howto.md
Labels: Accepted, Linguistic Suggestion

#891 Fix mistranslation
  articles/service-bus-messaging/service-bus-amqp-protocol-guide.md
Labels: Accepted

#892 Fix mistranslation
  articles/storage/common/storage-powershell-independent-clouds.md
Labels: Accepted, Linguistic Suggestion

#894 Fix mistranslation
  articles/azure-functions/functions-host-json-v1.md
Labels: Accepted, Linguistic Suggestion

#890 Update tutorial-sql-server-to-managed-instance.md
  articles/dms/tutorial-sql-server-to-managed-instance.md
Labels: Accepted, Linguistic Suggestion

#901 Fix mistranslation
  articles/azure-functions/functions-host-json.md
Labels: Accepted

#902 Fix mistranslation
  articles/azure-monitor/insights/solutions-resources-automation.md
Labels: Accepted

#893 Update sql-database-managed-instance-aad-security-tutorial.md
  articles/sql-database/sql-database-managed-instance-aad-security-tutorial.md
Labels: Linguistic Suggestion, Partially Accepted

#895 Update quickstart-sign-in-azure-notebooks.md
  articles/notebooks/quickstart-sign-in-azure-notebooks.md
Labels: Accepted, Linguistic Suggestion

#899 Update tutorial-create-run-jupyter-notebook.md
  articles/notebooks/tutorial-create-run-jupyter-notebook.md
Labels: Accepted, Linguistic Suggestion

#903 Fix mistranslation
  articles/azure-monitor/insights/solutions-resources-searches-alerts.md
Labels: Accepted

#904 Fix mistranslation
  articles/azure-monitor/platform/autoscale-understanding-settings.md
Labels: Accepted

#905 Fix mistranslation
  articles/azure-resource-manager/resource-group-authoring-templates.md
Labels: Accepted

#907 Fix mistranslation
  articles/azure-resource-manager/resource-group-template-functions-string.md
Labels: Accepted

#906 Fix mistranslation
  articles/azure-resource-manager/resource-group-template-functions-array.md
Labels: Accepted

#908 Fix mistranslation
  articles/blockchain/workbench/configuration.md
Labels: Accepted

#909 Fix mistranslation
  articles/blockchain/workbench/messages-overview.md
Labels: Accepted

#910 Fix mistranslation
  articles/cognitive-services/Speech/API-Reference-REST/websocketprotocol.md
Labels: Accepted

#912 Fix mistranslation
  articles/connectors/connectors-create-api-bingsearch.md
Labels: Accepted, Linguistic Suggestion

#914 Fix mistranslation
  articles/data-factory/concepts-pipelines-activities.md
Labels: Accepted

#915 Fix mistranslation
  articles/data-factory/connector-amazon-redshift.md
Labels: Accepted

#919 Fix mistranslation
  articles/data-factory/connector-azure-data-lake-storage.md
Labels: Accepted, Linguistic Suggestion

#920 Update index.yml
  articles/notebooks/index.yml
Labels: Accepted, Linguistic Suggestion

#921 Fix mistranslation
  articles/data-factory/connector-azure-data-lake-store.md
Labels: Accepted

#918 Update index.yml
  articles/lighthouse/index.yml
Labels: Accepted, Linguistic Suggestion
